apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: rtsp-stream-operator
  name: rtsp-stream-operator
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [ "apps" ]
    resources:
      - deployments
    verbs: [ "*" ]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "watch", "list"]
  - apiGroups: ["operators.example.com"]
    resources:
      - rtspstreams
    verbs: ["*"]