apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rtsp-stream-operator
  name: rtsp-stream-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtsp-stream-operator
subjects:
  - kind: ServiceAccount
    name: rtsp-stream-operator
    namespace: dev