apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rtspstreams.operators.example.com
spec:
  group: operators.example.com
  scope: Namespaced
  names:
    kind: RTSPStream
    listKind: RTSPStreamList
    plural: rtspstreams
    singular: rtspstream
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                authentification:
                  type: object
                  properties:
                    login:
                      type: string
                    password:
                      type: string
                servicePort:
                  type: object
                  required:
                    - port
                  properties:
                    name:
                      type: string
                    protocol:
                      type: string
                      default: TCP
                    port:
                      type: integer
                      format: int32
                containers:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      imagePullPolicy:
                        type: string
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                          requests:
                            type: object
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                      ports:
                        type: array
                        items:
                          type: object
                          required:
                            - containerPort
                          properties:
                            name:
                              type: string
                            protocol:
                              type: string
                              default: TCP
                            containerPort:
                              type: integer
                              format: int32
                      env:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            value:
                              type: string